version: '3'
services:
  todos:
    image: brenthmiras/todo-express-1
    environment:
      - MONGO_URI=mongodb://todos-mongo-srv:27017/todos
    ports:
      - 3000:3000
  todos-mongo-srv:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data:
