version: '3'
services:
  todos:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://todos-mongo-srv:27017/todos
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
  todos-mongo-srv:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongodb_data:
